// Services are now fetched from API /api/service-types
// This hardcoded data is kept for reference only
/*
export const services = [
  {
    id: 1,
    name: "Gói Cơ bản – Basic Maintenance",
    category: "Bảo dưỡng",
    icon: "🛠️",
    priceText: "1.000.000 VNĐ",
    priceValue: 1000000,
    summary:
      "Dành cho khách bảo dưỡng nhanh, chỉ thay những mục quan trọng nhất. Tần suất: 3–6 tháng / 5.000 km",
    details: [
      "1. Bảo Dưỡng Định Kỳ",
      "   • Thay dầu động cơ",
      "   • Kiểm tra hệ thống phanh",
      "   • Kiểm tra lọc gió (không thay)",
      "   • Kiểm tra lốp xe & áp suất lốp",
      "",
      "2. Sửa Chữa Động Cơ",
      "   • Chẩn đoán lỗi động cơ cơ bản",
      "   • Reset ECU nhẹ (nếu cần)",
      "",
      "3. Hệ Thống Phanh & Lốp",
      "   • Kiểm tra má phanh",
      "   • Kiểm tra đĩa phanh",
      "   • Kiểm tra độ mòn lốp",
      "",
      "4. Hệ Thống Điện",
      "   • Kiểm tra bình ắc quy",
      "   • Kiểm tra bóng đèn",
      "   • Kiểm tra hệ thống đánh lửa",
      "",
      "5. Điều Hoà & Làm Mát",
      "   • Kiểm tra gas lạnh",
      "   • Vệ sinh lọc gió điều hòa cơ bản",
      "",
      "6. Chăm Sóc Ngoại Thất",
      "   • Rửa xe cơ bản",
    ],
  },
  {
    id: 2,
    name: "Gói Tiêu chuẩn – Standard Maintenance",
    category: "Bảo dưỡng",
    icon: "⚡",
    priceText: "1.800.000 VNĐ",
    priceValue: 1800000,
    summary:
      "Gói phổ biến nhất, phù hợp đa số khách. Tần suất: 6–12 tháng / 10.000 km",
    details: [
      "1. Bảo Dưỡng Định Kỳ",
      "   • Thay dầu động cơ",
      "   • Thay lọc gió động cơ",
      "   • Kiểm tra lọc dầu",
      "   • Kiểm tra phanh & vệ sinh heo phanh",
      "",
      "2. Sửa Chữa Động Cơ",
      "   • Chẩn đoán lỗi động cơ chuyên sâu",
      "   • Vệ sinh họng hút & bướm ga",
      "   • Điều chỉnh động cơ nhẹ",
      "",
      "3. Hệ Thống Phanh & Lốp",
      "   • Cân bằng lốp",
      "   • Kiểm tra độ đảo lốp",
      "   • Vệ sinh má phanh",
      "",
      "4. Hệ Thống Điện",
      "   • Kiểm tra toàn bộ hệ thống điện",
      "   • Test ắc quy bằng máy chuyên dụng",
      "   • Kiểm tra cảm biến ABS, TPMS",
      "",
      "5. Điều Hoà & Làm Mát",
      "   • Vệ sinh dàn lạnh cơ bản",
      "   • Bổ sung gas lạnh (nếu thiếu)",
      "   • Kiểm tra két nước làm mát",
      "",
      "6. Chăm Sóc Ngoại Thất",
      "   • Rửa xe chuyên nghiệp",
      "   • Dưỡng bóng sơn nhẹ",
    ],
  },
  {
    id: 3,
    name: "Gói Cao cấp – PREMIUM / FULL Maintenance",
    category: "Bảo dưỡng",
    icon: "✨",
    priceText: "3.900.000 VNĐ",
    priceValue: 3900000,
    summary:
      "Gói full bảo dưỡng toàn diện. Tần suất: 12 tháng / 20.000 km hoặc xe cao cấp",
    details: [
      "1. Bảo Dưỡng Định Kỳ",
      "   • Thay dầu động cơ cao cấp",
      "   • Thay lọc gió động cơ",
      "   • Thay lọc dầu",
      "   • Kiểm tra toàn bộ phanh & thay má phanh (nếu mòn)",
      "   • Kiểm tra & cân chỉnh toàn bộ hệ thống gầm",
      "",
      "2. Sửa Chữa Động Cơ",
      "   • Chẩn đoán chuyên sâu ECU",
      "   • Vệ sinh buồng đốt",
      "   • Vệ sinh kim phun",
      "   • Thay bugi (nếu xe xăng)",
      "",
      "3. Hệ Thống Phanh & Lốp",
      "   • Cân bằng lốp",
      "   • Đảo lốp",
      "   • Hiệu chỉnh góc đặt bánh xe",
      "   • Trét keo chống ồn má phanh",
      "",
      "4. Hệ Thống Điện",
      "   • Kiểm tra toàn bộ hệ thống điện",
      "   • Kiểm tra & cập nhật ECU",
      "   • Kiểm tra tất cả cảm biến quan trọng (ABS, O2, MAP, TPS…)",
      "",
      "5. Điều Hoà & Làm Mát",
      "   • Vệ sinh dàn lạnh chuyên sâu",
      "   • Thay lọc gió điều hòa",
      "   • Kiểm tra hệ thống két nước",
      "   • Thay nước làm mát",
      "",
      "6. Chăm Sóc Ngoại Thất",
      "   • Rửa xe detailing",
      "   • Đánh bóng sơn xe",
      "   • Phủ ceramic (bản nhẹ)",
      "   • Vệ sinh nội thất toàn diện",
    ],
  },
];
*/

export const serviceCenters = [
  {
    id: 1,
    name: "Chi nhánh 1 - CarCare Quận 1",
    address: "123 Lê Lợi, Quận 1",
    city: "Hồ Chí Minh",
    phone: "024-3456-7890",
    workingHours: "Thứ 2 - Thứ 7: 8:00 - 18:00",
    icon: "🏢",
  },
  {
    id: 2,
    name: "Chi nhánh 2 - CarCare Thủ Đức",
    address: "456 Võ Văn Ngân, Thủ Đức",
    city: "Hồ Chí Minh",
    phone: "028-9876-5432",
    workingHours: "Thứ 2 - Thứ 7: 8:00 - 18:00",
    icon: "🏢",
  },
];

export const timeSlots = [
  "08:00",
  "08:30",
  "09:00",
  "09:30",
  "10:00",
  "10:30",
  "11:00",
  "11:30",
  "13:00",
  "13:30",
  "14:00",
  "14:30",
  "15:00",
  "15:30",
  "16:00",
  "16:30",
];

